### PR TITLE
2 support for custom api urls

### LINKED ISSUE #2: Support for custom API URLs
In the settings section of this plugin, add a text input field to allow the user to configure the endpoint which this plugin shall send data to (default is `https://wakatime.com/api`, but might be set to `https://wakapi.dev/api` or `https://wakapi.your-server.tld/api` then). Then, replace references to the [hard-coded](https://github.com/muety/chrome-wakapi/blob/34f179a8ebcf283c304598953de002bc73c1c019/src/config/config.ts#L119) URL by that user input.

### PR DESCRIPTION
**Pull request by qhantom**
Closes #2 

This branch is based on #5 and should be merged afterwards.

I just added an input field and implemented it into the browser storage flow. Additionally, I replaced the heartbeat URL of wakatime with the one of wakapi. There are other env variables that point to wakatime such as `logoutUserUrl`. I didn't change it in this PR since it's out of scope. That must be changed as well @muety 

So the hierarchy of a set URL is:
1. custom user input (stored in browser storage), this feature
2. env variable (configured in `webpack.config.ts`)
3. fallback value if 2. is not set (configured in `config.ts`)

### CODE REVIEW

**Comment by muety** [comment]
Thank you so much for this contribution! :raised_hands: 🤍

I realized besides `heartbeatApiUrl` there is also `summariesApiUrl` and `currentUserApiUrl`, all of which are currently absolute URLs, defaulting to `https://wakatime.com/...`. We'll need to adapt them as well. 

I think best option would be to allow for configuring an API base URL (e.g. `https://wakapi.dev/api/v1` or `https://wakatime.com/api/v1`, respectively) and then construct the above three endpoints relative to it.

Let me know if you're you're keen to get another crack on this, otherwise I'll have a look myself :-).

**Comment by qhantom** [comment]
> Thank you so much for this contribution! 🙌 🤍
> 
> I realized besides `heartbeatApiUrl` there is also `summariesApiUrl` and `currentUserApiUrl`, all of which are currently absolute URLs, defaulting to `https://wakatime.com/...`. We'll need to adapt them as well.
> 
> I think best option would be to allow for configuring an API base URL (e.g. `https://wakapi.dev/api/v1` or `https://wakatime.com/api/v1`, respectively) and then construct the above three endpoints relative to it.
> 
> Let me know if you're you're keen to get another crack on this, otherwise I'll have a look myself :-).

Sure <3

I totally agree with you on the base URL solution. I'd be happy to implement it. One question for my understanding: there aren't cases in which the wakapi **and** wakatime endpoints can work in conjunction?

**Comment by muety** [comment]
> there aren't cases in which the wakapi and wakatime endpoints can work in conjunction?

No, user accounts, API keys, etc. are different between Wakapi and Wakatime. A legitimate use case could be to use both in parallel though, that is, replicate data to both services. But this wouldn't be handled by the plug-in, but rather through Wakapi's forwarding functionality.

**Comment by muety** [comment]
Support for custom API URLs has been implemented upstream in the meanwhile, see https://github.com/wakatime/chrome-wakatime/pull/179. Looks like we won't need this anymore, sorry man!

**Pull request closed without merging**
